# https://www.wilsonwilson.dev/articles/flutter-build-yaml/

targets:
  $default:
    builders:
      freezed|freezed:
        enabled: true
        generate_for:
          - "lib/core/models/certificate.dart"
          - "lib/core/models/dialog_state.dart"
          - "lib/core/models/screen_size.dart"
