name: certificate_maker
description: A Flutter project to generate IKMF certificates.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^1.0.4
  path_provider: ^2.0.11
  printing: ^5.9.1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.4
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  lint: ^1.8.2

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "#424242"
  image: assets/images/logo.png
  android: true
  ios: true

flutter_gen:
  output: lib/core/assets/

flutter:
  uses-material-design: true
  assets:
    - assets/images/
